name: jay
favicon: null
layout_spectrum: 0.4194322202820331
typography_spectrum: 0.2571510311681777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.36966817593201995
  lightness: 0.030166127486154437
  saturation: 0.7308590819593519
  rhythmicContrast: 0.23776194266974926
purpose: []
